language: cpp

compiler:
    - gcc

install:
    - sudo apt-get update
    - sudo apt install libtiff5-dev
    - sudo apt install cmake
    - sudo apt install libboost-all-dev

script:
    - rm -rf ./build/*
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - ./s3it-tech-challenge
